### ISSUE TITLE
object has no attribute 'loadInputs'

### ISSUE THREAD

**Issue by adriantre** [d6t/d6tflow#13]
Hi! Just started trying out d6tflow.

I seem to have run into a problem:
When running:

`class TaskCombineData(d6tflow.tasks.TaskPqPandas):

    def requires(self):
        return TaskGetData1(), TaskGetData2()

    def run(self):
        df_data1, df_data2 = self.loadInputs()
        data = pd.concat([df_likes, df_dislikes])
        self.save(data)`

I get the following error:
'TaskCombineData' object has no attribute 'loadInputs'

Have I misunderstood the usage mentioned [here](https://d6tflow.readthedocs.io/en/latest/tasks.html?highlight=loadinputs#load-input-data
)?

d6tcollect==1.0.5
d6tflow==0.1.5

**Comment by d6tdev** [comment]
This for pointing this out, [updated the docs](https://d6tflow.readthedocs.io/en/latest/tasks.html?highlight=loadinputs#load-input-data)
