### ISSUE TITLE
luigi related signal only works in main thread

### ISSUE THREAD

**Issue by bacross** [d6t/d6tflow#15]
Within a flask app that is a REST API with a post functionality, I am trying to post parameters to a d6tflow task to run the task with the posted params.  Luigi throws a ValueError: signal only works in main thread when calling luigi/worker.py which in turn calls python 3.7 signal.py

**Comment by d6tdev** [comment]
This seems to be a problem only in linux when you run flask from the command line. Windows does not have the problem and when you correctly deploy the flask app using gunicorn wsgi you don't get this problem. Closing for now

**Comment by Fire-Hound** [comment]
There's a working solution for this. Just add the below luigi.cfg file in the directory of your flask app.

*luigi.cfg*

```
[worker]
no_install_shutdown_handler=True
```

This is a problem specific to Linux. Should work fine without the cfg file in other platforms.

**Comment by ilvacca** [comment]
> There's a working solution for this. Just add the below luigi.cfg file in the directory of your flask app.
> 
> _luigi.cfg_
> 
> ```
> [worker]
> no_install_shutdown_handler=True
> ```
> 
> This is a problem specific to Linux. Should work fine without the cfg file in other platforms.

I had the same problem while deploying in an Azure Function App. Solved with this suggestion. Thank you.
