### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by acardosoj** [d6t/d6tflow#18]
Hello, 

I've been using d6tflow to run multiple ML models with different parameters. In some executions I trained over 20K models.

I'm using 10 workers in a linux environment and after some time I get an error of two many open files.  I do not open any file in the custom code inside my tasks.  I'm using TaskPqPandas and TaskPickle targets to this for me....

Any help on this issue would be appreciated. 

Thanks!

**Comment by acardosoj** [comment]
The problem was at the PickleTarget.  There're calls to the _open_ method without the _with_ clause

**Comment by d6tdev** [comment]
Thanks for flagging. Fixed in v0.1.8 can you [install dev version](https://github.com/d6t/d6tflow#installation) and check it works?

**Comment by d6tdev** [comment]
haven't heard back, assume it's fixed, reopen if not
