### ISSUE TITLE
Task type to output txt files.

### ISSUE THREAD

**Issue by NeuroWinter** [d6t/d6tflow#8]
I am currently working with AWS SageMaker, and it requires a text file to be uploaded as the data.

Would we be able to implement a Task that will output a simple text file?

**Comment by d6tdev** [comment]
Try this
```
class TaskTXTPandas(d6tflow.tasks.TaskCSVPandas):
    target_ext = 'txt'
```

**Comment by d6tdev** [comment]
Closing for now, reopen if it doesnt work
