### ISSUE TITLE
Add `verbose` flag to disable all the output from `d6tflow.run(Task())`

### ISSUE THREAD

**Issue by MarcoGorelli** [d6t/d6tflow#9]
If I run
```
d6tflow.run(Task())
```
I get lots of output (the 'Luigi execution summary').

Granted, this is useful information, but sometimes I'd like to be able to just run a task without getting so much output.

Could we add a flag (e.g. `verbose`) which, if set to `False`, just runs the task without the Luigi execution summary getting displayed?

This is something I could work on, if you'd consider it worthwhile.

**Comment by d6tdev** [comment]
Already implemented, if you like to change/improve pls reopen 
https://d6tflow.readthedocs.io/en/latest/run.html#reducing-logging-output

**Comment by d6tdev** [comment]
Note that we just made some changes to reduce the luigi logging output which most users considered excessive. See https://d6tflow.readthedocs.io/en/latest/run.html#hiding-execution-output
